---
- hosts: localhost
  remote_user: root
  include_vars: openshift_install_vars

  tasks:
  - name: install OpenShift with IPI
    command: /usr/bin/openshift-installer --dir /opt/openshift-install/{{ clustername }}/installconfig.yaml
